-- Schema do Banco de Dados para AstroJump (Supabase)

-- Habilita a extensão para geração de UUIDs aleatórios
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Tabela de Jogadores (players)
CREATE TABLE IF NOT EXISTS public.players (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    bio TEXT DEFAULT 'Astro Saltador!',
    best_score INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabela de Classificação/Pontuações (leaderboard)
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id UUID REFERENCES public.players(id) ON DELETE CASCADE NOT NULL,
    score INTEGER NOT NULL,
    skin INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Índices para otimização de consultas e ordenação de pontuação
CREATE INDEX IF NOT EXISTS leaderboard_score_idx ON public.leaderboard (score DESC);

-- =========================================================================
-- OBSERVAÇÃO SOBRE SEGURANÇA (RLS - Row Level Security)
-- =========================================================================
-- Como a autenticação deste jogo é feita de maneira customizada na tabela `players`
-- (utilizando a chave pública anon do Supabase no front-end sem o Supabase Auth nativo),
-- caso a segurança RLS esteja habilitada em seu projeto Supabase, você precisará
-- liberar acessos públicos (anon) para leitura e inserção de dados.
--
-- Caso prefira simplificar para testes/desenvolvimento rápido, você pode desativar
-- o RLS nas tabelas executando os seguintes comandos:
--
-- ALTER TABLE public.players DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.leaderboard DISABLE ROW LEVEL SECURITY;
--
-- Se preferir manter o RLS ativo, execute as políticas abaixo para permitir o fluxo:

-- ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- -- Políticas para 'players'
-- CREATE POLICY "Permitir leitura pública de perfis" ON public.players FOR SELECT USING (true);
-- CREATE POLICY "Permitir cadastro público" ON public.players FOR INSERT WITH CHECK (true);
-- CREATE POLICY "Permitir atualização de perfil próprio" ON public.players FOR UPDATE USING (true);

-- -- Políticas para 'leaderboard'
-- CREATE POLICY "Permitir leitura pública do ranking" ON public.leaderboard FOR SELECT USING (true);
-- CREATE POLICY "Permitir envio público de pontuações" ON public.leaderboard FOR INSERT WITH CHECK (true);
